### ISSUE TITLE
About LRA calculation

### ISSUE THREAD

**Issue by granadet17** [cszyzhang/riconv2#7]
Thank you for sharing the code.

I have a question about the LRA calculation.
Why didn't you remove the sign ambiguity of the eigen vectors like SHOT feature?
Is there any reason?

**Comment by cszyzhang** [comment]
1. LRA is much more robust than the LRF of SHOT. Please check Fig. 8 of our IJCV paper which clearly shows this. 
2. Sign ambiguity cannot be removed in many cases especially when the local shape is like a disk or lacking sufficient geometric features. Moreover, the noise can further deteriorate this. Thus, we proposed LRA which has no sign ambiguity problem.

**Comment by granadet17** [comment]
Thanks for the reply.
I understand now.

I would like to ask one more question about implementation.
https://github.com/cszyzhang/riconv2/blob/134122e90305c5d38d0d2f5ec151e908e44f062b/models/riconv2_utils.py#L216-L241

In this function, you wrote
https://github.com/cszyzhang/riconv2/blob/134122e90305c5d38d0d2f5ec151e908e44f062b/models/riconv2_utils.py#L236
but, I think the first is not the vec_ref.

**Comment by cszyzhang** [comment]
Thanks for reporting that line of comment. Yes. the first is not the vec_ref. The vec_ref is the one with largest distance from the center point, while the first one is the center point by itself whose vec is always [0,0,0]. So, we force its sign to 1 to avoid two identical dots after sign operation (Line 237). Otherwise, the 1st dot value and the ref dot value will become identical. I have updated that line of comment. Hope this clarifies.

**Comment by granadet17** [comment]
Thank you.
Shouldn't you set the sign of vec_ref manually since the cross product of vec_ref and vec_ref is also [0, 0, 0].

**Comment by cszyzhang** [comment]
So, set one of them to differentiate it from the other.

**Comment by granadet17** [comment]
I'm sorry, I misunderstood.

Thank you.
